### ISSUE TITLE
Support React.Fragment Wrappers

### ISSUE THREAD

**Issue by lxe** [fusionjs/fusion-react-async#77]
### Type of issue

Bug

### Description

Getting a red error when passing a `<Fragment>` to `App()`:

```javascript
export default async function() {
  const app = new App(
    <Fragment>
    //...
```

### Current behavior

Redbox that says:

```
TypeError: type is not a function
prepareElement
xxx/node_modules/fusion-react-async/src/prepare.js:48:29
_prepare
xxx/node_modules/fusion-react-async/src/prepare.js:65:10
Promise.all.React__default.Children.toArray.map.child
xxx/node_modules/fusion-react-async/src/prepare.js:68:9
prepareElement.then
xxx/node_modules/fusion-react-async/src/prepare.js:67:40
process._tickCallback
internal/process/next_tick.js:188:7
```

### Steps to reproduce

1. Pass a [Fragment](https://reactjs.org/docs/fragments.html) to App() (See above)
2. `yarn run fusion dev`

### Your environment

* fusion-react-async version: `1.0.2`

* Node.js version (`node --version`): `v8.9.4`

* npm version (`npm --version`): `5.6.0`

* Operating System: `17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`

**Comment by mlmorg** [comment]
Fixed by #84
